version: "3"

services:

    mq:
        image: rabbitmq
        volumes:
            - mq-data:/var/lib/rabbitmq
        restart: unless-stopped

    redis:
        image: redis
        volumes:
            - redis-data:/data
        restart: unless-stopped

    db:
        image: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        restart: unless-stopped

    web:
        build: .
        entrypoint: python manage.py
        command: runserver 0.0.0.0:8814
        volumes:
            - .:/app
        ports:
            - "8814:8814"
        depends_on:
            - db
            - mq
        restart: unless-stopped

    # The steamworker only and exclusively processes Steam requests
    # to mitigate and scale rate limits. It does not require database
    # access.
    steamworker:
        build: .
        entrypoint: celery -A proj worker -Q steamworker -n steamworker@%h
        hostname: localhost
        command: -l info
        volumes:
            - .:/app
        depends_on:
            - mq
            - redis
        restart: unless-stopped
        environment:
            C_FORCE_ROOT: 1
            DJANGO_SETTINGS_MODULE: proj.settings.steamworker

    # The default worker processes all other tasks.
    worker:
        build: .
        entrypoint: celery -A proj worker -n worker@%h
        hostname: localhost
        command: -l info
        volumes:
            - .:/app
        depends_on:
            - db
            - mq
            - redis
        restart: unless-stopped
        environment:
            C_FORCE_ROOT: 1

    flower:
        build: .
        entrypoint: celery -A proj flower
        command: --basic_auth=outermosttail:vaporizedsteam
        ports:
            - "5555:5555"
        depends_on:
            - mq
            - redis
        restart: unless-stopped
        environment:
            DEBUG: 0

    graph:
        image: neo4j
        ports:
            - "7474:7474"
            - "7687:7687"
        volumes:
            - graph-data:/data
        restart: unless-stopped

    adminer:
        image: adminer
        restart: always
        depends_on:
            - db
        ports:
          - 8081:8080

volumes:
    db-data:
    mq-data:
    redis-data:
    graph-data:
