version: "3"

services:

    mq:
        image: rabbitmq
        volumes:
            - mq-data:/var/lib/rabbitmq
        restart: unless-stopped

    db:
        image: postgres
        volumes:
            - db-data:/var/lib/postgresql/data
        restart: unless-stopped

    web:
        build: .
        entrypoint: python manage.py
        command: runserver 0.0.0.0:8814
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - db
            - mq
        restart: unless-stopped

    worker:
        build: .
        entrypoint: celery -A proj worker
        command: -l info
        volumes:
            - .:/app
        depends_on:
            - mq
        restart: unless-stopped

    scheduler:
        build: .
        entrypoint: celery -A proj beat
        command: -l debug
        volumes:
            - .:/app
        depends_on:
            - mq
        restart: unless-stopped

volumes:
    db-data:
    mq-data:
