# Generated by Django 2.2 on 2019-04-01 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='app ID')),
                ('type', models.CharField(max_length=32, verbose_name='app type')),
                ('name', models.TextField(verbose_name='app name')),
                ('info', models.BinaryField(blank=True, null=True, verbose_name='raw app info')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified on')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='steamtail.App', verbose_name='parent app')),
            ],
            options={
                'verbose_name': 'app',
                'verbose_name_plural': 'apps',
            },
        ),
    ]
