# Generated by Django 2.2 on 2019-04-02 14:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='app ID')),
                ('type', models.CharField(max_length=32, null=True, verbose_name='app type')),
                ('name', models.TextField(verbose_name='app name')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('modified_on', models.DateTimeField(auto_now=True, verbose_name='modified on')),
                ('release_date', models.DateField(null=True, verbose_name='release date')),
                ('unknown', models.BooleanField(null=True, verbose_name='unknown')),
                ('raw_info', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='raw app info')),
                ('raw_store_page', models.BinaryField(null=True, verbose_name='raw store page')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='steamtail.App', verbose_name='parent app')),
            ],
            options={
                'verbose_name': 'app',
                'verbose_name_plural': 'apps',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='tag ID')),
                ('name', models.CharField(max_length=255, verbose_name='tag name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AppTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.PositiveIntegerField(verbose_name='votes')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steamtail.App')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steamtail.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='app',
            name='tags',
            field=models.ManyToManyField(related_name='apps', through='steamtail.AppTag', to='steamtail.Tag', verbose_name='tags'),
        ),
    ]
