# Generated by Django 2.2 on 2019-04-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='app type'),
        ),
    ]
