# Generated by Django 2.2 on 2019-04-03 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='coming_soon',
            field=models.BooleanField(null=True, verbose_name='coming soon'),
        ),
        migrations.AddField(
            model_name='app',
            name='is_free',
            field=models.BooleanField(null=True, verbose_name='is free'),
        ),
        migrations.AddField(
            model_name='app',
            name='short_description',
            field=models.TextField(null=True, verbose_name='short description'),
        ),
    ]
