# Generated by Django 2.2 on 2019-04-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0002_auto_20190401_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['id', 'name'], 'verbose_name': 'app', 'verbose_name_plural': 'apps'},
        ),
        migrations.AddField(
            model_name='app',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='release date'),
        ),
    ]
