# Generated by Django 2.2 on 2019-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0003_auto_20190401_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='tag name')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='app',
            name='tags',
            field=models.ManyToManyField(to='steamtail.Tag', verbose_name='tags'),
        ),
    ]
