# Generated by Django 2.2 on 2019-04-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0004_auto_20190401_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='tags',
            field=models.ManyToManyField(related_name='apps', to='steamtail.Tag', verbose_name='tags'),
        ),
    ]
