# Generated by Django 2.2 on 2019-04-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0005_auto_20190401_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='store_page_html',
            field=models.BinaryField(blank=True, null=True, verbose_name='store page html'),
        ),
        migrations.AddField(
            model_name='app',
            name='store_page_retrieved_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='store page retrieved on'),
        ),
    ]
