# Generated by Django 2.2 on 2019-04-04 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0005_auto_20190403_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(editable=False, primary_key=True, serialize=False, verbose_name='steam64 id')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.AlterUniqueTogether(
            name='apptag',
            unique_together={('app', 'tag')},
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_played', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='hours played')),
                ('last_played', models.DateTimeField(null=True, verbose_name='last played')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steamtail.App')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steamtail.User')),
            ],
            options={
                'unique_together': {('user', 'app')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='apps',
            field=models.ManyToManyField(related_name='users', through='steamtail.UserApp', to='steamtail.App', verbose_name='apps'),
        ),
    ]
