# Generated by Django 2.2 on 2019-04-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0006_auto_20190404_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='steamtail.User', verbose_name='friends'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_visited_on',
            field=models.DateTimeField(null=True, verbose_name='last visited on'),
        ),
    ]
