# Generated by Django 2.2 on 2019-04-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0007_auto_20190406_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='steamtail.User'),
        ),
    ]
