# Generated by Django 2.2 on 2019-04-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0009_auto_20190406_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['id'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(null=True, verbose_name='is profile private'),
        ),
    ]
