# Generated by Django 2.2 on 2019-04-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0010_auto_20190406_2210'),
    ]

    operations = [
        migrations.RenameField(
            'user',
            'last_visited_on',
            'friends_last_checked_on',
        ),
        migrations.AddField(
            model_name='user',
            name='is_ownership_public',
            field=models.BooleanField(null=True, verbose_name='is ownership public'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_playtime_public',
            field=models.BooleanField(null=True, verbose_name='is playtime public'),
        ),
    ]
