# Generated by Django 2.2 on 2019-04-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0012_auto_20190409_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apps_last_checked_on',
            field=models.DateTimeField(null=True, verbose_name='apps last checked on'),
        ),
    ]
