# Generated by Django 2.2 on 2019-04-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0013_user_apps_last_checked_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='last_played',
        ),
    ]
