# Generated by Django 2.2 on 2019-04-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0015_auto_20190409_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_public',
            field=models.BooleanField(null=True, verbose_name='is profile public'),
        ),
    ]
