# Generated by Django 2.2 on 2019-04-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0016_auto_20190409_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apptag',
            options={'ordering': ['-votes']},
        ),
        migrations.AddField(
            model_name='apptag',
            name='share',
            field=models.FloatField(null=True, verbose_name='share of votes'),
        ),
    ]
