# Generated by Django 2.2 on 2019-04-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0018_app_tag_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='negative_reviews',
            field=models.PositiveIntegerField(null=True, verbose_name='negative review count'),
        ),
        migrations.AddField(
            model_name='app',
            name='positive_reviews',
            field=models.PositiveIntegerField(null=True, verbose_name='positive review count'),
        ),
    ]
