# Generated by Django 2.2 on 2019-04-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0019_auto_20190413_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='review_score',
            field=models.FloatField(null=True, verbose_name='review score'),
        ),
    ]
