# Generated by Django 2.2 on 2019-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0020_app_review_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='raw_info',
        ),
        migrations.RemoveField(
            model_name='app',
            name='raw_store_page',
        ),
        migrations.AddField(
            model_name='app',
            name='release_date_text',
            field=models.CharField(max_length=255, null=True, verbose_name='release date text'),
        ),
    ]
