# Generated by Django 2.2 on 2019-04-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steamtail', '0022_app_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='exclude',
            field=models.BooleanField(default=False, verbose_name='exclude from computations'),
        ),
    ]
